<?php

namespace ActivitiesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityParticipantRepository extends EntityRepository
{
}
