<?php

namespace ActivitiesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityPhotoRepository extends EntityRepository
{
}
