<?php

namespace ActivitiesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityIdeaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityIdeaRepository extends EntityRepository
{
}
