activities:
    resource: "@ActivitiesBundle/Controller/"
    type:     annotation
    prefix:   /activities

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /users

app:
    resource: '@AppBundle/Controller/'
    type: annotation

_liip_imagine:
  resource: '@LiipImagineBundle/Resources/config/routing.xml'