security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_BDE: ROLE_BDE
        ROLE_ETUDIANT: ROLE_ETUDIANT
        ROLE_TUTEUR: [ROLE_TUTEUR, ROLE_ETUDIANT]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
                login_path: fos_user_security_login
                use_forward: false
                check_path: fos_user_security_check
                failure_path: null
                default_target_path: /
                remember_me: true
                require_previous_session: false
            remember_me:
                key: %secret%
                lifetime: 3600
                path: /
                domain: ~
            logout: 
                path: fos_user_security_logout
                target: /
            anonymous: true